<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "fetschersite"
 *
 * Auto generated by Extension Builder 2016-11-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Burka Metall Website',
	'description' => 'Another Fetscher Website',
	'category' => 'distribution',
	'author' => 'Joe Schäfer',
	'author_email' => 'mail@schaefer-webentwicklung.de',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '2.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '8.7.24-8.7.99',
			'gridelements' => '',
			'bootstrap_grids' => '1.3.0-1.4.99',
			'fsc_layout_wrap' => '',
			'mask' => '',
			'powermail' => '',
			'realurl' => '',
			'dd_googlesitemap' => '',
			'jh_magnificpopup' => '',
			'cs_seo' => '',
			'sourceopt' => '',
			// Sysextensions
			'opendocs' => '',
			'recycler' => '',
			'vhs' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
			'scriptmerger' => '',
			'unroll' => '',
			'go_maps_ext' => '',
			'fsc_layout_wrap' => '',
			'frontend_editing' => '',
			'lib_js_lazysizes' => '', // https://github.com/joekolade/lib_js_lazysizes
			'cookieconsent2' => '',
            'fluid_styled_responsive_images' => ''
		),
	),
);
